// Code generated by MockGen. DO NOT EDIT.
// Source: activity.go

// Package mock_interactor is a generated GoMock package.
package mock_interactor

import (
	gomock "github.com/golang/mock/gomock"
	entity "homepage/pkg/domain/entity"
	reflect "reflect"
)

// MockActivityInteractor is a mock of ActivityInteractor interface
type MockActivityInteractor struct {
	ctrl     *gomock.Controller
	recorder *MockActivityInteractorMockRecorder
}

// MockActivityInteractorMockRecorder is the mock recorder for MockActivityInteractor
type MockActivityInteractorMockRecorder struct {
	mock *MockActivityInteractor
}

// NewMockActivityInteractor creates a new mock instance
func NewMockActivityInteractor(ctrl *gomock.Controller) *MockActivityInteractor {
	mock := &MockActivityInteractor{ctrl: ctrl}
	mock.recorder = &MockActivityInteractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockActivityInteractor) EXPECT() *MockActivityInteractorMockRecorder {
	return m.recorder
}

// GetAll mocks base method
func (m *MockActivityInteractor) GetAll() ([]*entity.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]*entity.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll
func (mr *MockActivityInteractorMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockActivityInteractor)(nil).GetAll))
}

// GetByID mocks base method
func (m *MockActivityInteractor) GetByID(id int) (*entity.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*entity.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID
func (mr *MockActivityInteractorMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockActivityInteractor)(nil).GetByID), id)
}

// GetUpcoming mocks base method
func (m *MockActivityInteractor) GetUpcoming() ([]*entity.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpcoming")
	ret0, _ := ret[0].([]*entity.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUpcoming indicates an expected call of GetUpcoming
func (mr *MockActivityInteractorMockRecorder) GetUpcoming() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpcoming", reflect.TypeOf((*MockActivityInteractor)(nil).GetUpcoming))
}

// GetForNotification mocks base method
func (m *MockActivityInteractor) GetForNotification() ([]*entity.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForNotification")
	ret0, _ := ret[0].([]*entity.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForNotification indicates an expected call of GetForNotification
func (mr *MockActivityInteractorMockRecorder) GetForNotification() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForNotification", reflect.TypeOf((*MockActivityInteractor)(nil).GetForNotification))
}

// Create mocks base method
func (m *MockActivityInteractor) Create(activity, showDate, date, annotation string, isImportant, isNotify int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", activity, showDate, date, annotation, isImportant, isNotify)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockActivityInteractorMockRecorder) Create(activity, showDate, date, annotation, isImportant, isNotify interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockActivityInteractor)(nil).Create), activity, showDate, date, annotation, isImportant, isNotify)
}

// UpdateByID mocks base method
func (m *MockActivityInteractor) UpdateByID(id int, activity, showDate, date, annotation string, isImportant, isNotify int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", id, activity, showDate, date, annotation, isImportant, isNotify)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID
func (mr *MockActivityInteractorMockRecorder) UpdateByID(id, activity, showDate, date, annotation, isImportant, isNotify interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockActivityInteractor)(nil).UpdateByID), id, activity, showDate, date, annotation, isImportant, isNotify)
}

// DeleteByID mocks base method
func (m *MockActivityInteractor) DeleteByID(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID
func (mr *MockActivityInteractorMockRecorder) DeleteByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockActivityInteractor)(nil).DeleteByID), id)
}
