version: '3.7'
services:
  app:
    build:
      context: ./go
      dockerfile: ./Dockerfile
      target: build
    container_name: semi-homepage-app
    restart: always
    environment:
      MARIA_USER: root
      MARIA_PASSWORD: password
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - ./go:/go/src/app
    depends_on:
      - db
    links:
      - db
    command: realize start
  db:
    image: mysql:5.7
    container_name: semi-homepage-db
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homepage
      MYSQL_USER: worker
      MYSQL_PASSWORD: password
    volumes:
      - ./db/init.d/dump.sql:/docker-entrypoint-initdb.d
    ports:
      - "3300:3306"
    # expose:
    #   - "3306"