version: "3.7"
services:
  app:
    build:
      context: ./go
      dockerfile: ./Dockerfile
      target: build
    container_name: semi-homepage-app
    restart: always
    environment:
      MARIA_USER: root
      MARIA_PASSWORD: password
      MARIA_PROTOCOL: tcp
      MARIA_TARGET: "db:3306"
      MARIA_DB: homepage
    ports:
      - "8080:8080"
    volumes:
      - ./go:/go/src/app
    depends_on:
      - db
    command: realize start
  db:
    image: mariadb:10.0.32
    container_name: semi-homepage-db
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: homepage
      MYSQL_USER: worker
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/init.d:/docker-entrypoint-initdb.d
    ports:
      - "13306:3306"