// Code generated by MockGen. DO NOT EDIT.
// Source: equipment.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	gomock "github.com/golang/mock/gomock"
	entity "homepage/pkg/domain/entity"
	reflect "reflect"
)

// MockEquipment is a mock of Equipment interface
type MockEquipment struct {
	ctrl     *gomock.Controller
	recorder *MockEquipmentMockRecorder
}

// MockEquipmentMockRecorder is the mock recorder for MockEquipment
type MockEquipmentMockRecorder struct {
	mock *MockEquipment
}

// NewMockEquipment creates a new mock instance
func NewMockEquipment(ctrl *gomock.Controller) *MockEquipment {
	mock := &MockEquipment{ctrl: ctrl}
	mock.recorder = &MockEquipmentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockEquipment) EXPECT() *MockEquipmentMockRecorder {
	return m.recorder
}

// GetAll mocks base method
func (m *MockEquipment) GetAll() ([]*entity.Equipment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]*entity.Equipment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll
func (mr *MockEquipmentMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockEquipment)(nil).GetAll))
}

// GetByID mocks base method
func (m *MockEquipment) GetByID(id int) (*entity.Equipment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*entity.Equipment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID
func (mr *MockEquipmentMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockEquipment)(nil).GetByID), id)
}

// Create mocks base method
func (m *MockEquipment) Create(name, comment string, stock, tagID int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", name, comment, stock, tagID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockEquipmentMockRecorder) Create(name, comment, stock, tagID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEquipment)(nil).Create), name, comment, stock, tagID)
}

// UpdateByID mocks base method
func (m *MockEquipment) UpdateByID(id int, name, comment string, stock, tagID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", id, name, comment, stock, tagID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID
func (mr *MockEquipmentMockRecorder) UpdateByID(id, name, comment, stock, tagID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockEquipment)(nil).UpdateByID), id, name, comment, stock, tagID)
}

// DeleteByID mocks base method
func (m *MockEquipment) DeleteByID(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID
func (mr *MockEquipmentMockRecorder) DeleteByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockEquipment)(nil).DeleteByID), id)
}
