// Code generated by MockGen. DO NOT EDIT.
// Source: research.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	gomock "github.com/golang/mock/gomock"
	entity "homepage/pkg/domain/entity"
	reflect "reflect"
)

// MockResearch is a mock of Research interface
type MockResearch struct {
	ctrl     *gomock.Controller
	recorder *MockResearchMockRecorder
}

// MockResearchMockRecorder is the mock recorder for MockResearch
type MockResearchMockRecorder struct {
	mock *MockResearch
}

// NewMockResearch creates a new mock instance
func NewMockResearch(ctrl *gomock.Controller) *MockResearch {
	mock := &MockResearch{ctrl: ctrl}
	mock.recorder = &MockResearchMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockResearch) EXPECT() *MockResearchMockRecorder {
	return m.recorder
}

// GetAll mocks base method
func (m *MockResearch) GetAll() ([]*entity.Research, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]*entity.Research)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll
func (mr *MockResearchMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockResearch)(nil).GetAll))
}

// GetByID mocks base method
func (m *MockResearch) GetByID(id int) (*entity.Research, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*entity.Research)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID
func (mr *MockResearchMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockResearch)(nil).GetByID), id)
}

// Create mocks base method
func (m *MockResearch) Create(title, author, file, comment string, activation int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", title, author, file, comment, activation)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockResearchMockRecorder) Create(title, author, file, comment, activation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockResearch)(nil).Create), title, author, file, comment, activation)
}

// UpdateByID mocks base method
func (m *MockResearch) UpdateByID(id int, title, author, file, comment string, activation int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", id, title, author, file, comment, activation)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID
func (mr *MockResearchMockRecorder) UpdateByID(id, title, author, file, comment, activation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockResearch)(nil).UpdateByID), id, title, author, file, comment, activation)
}

// DeleteByID mocks base method
func (m *MockResearch) DeleteByID(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID
func (mr *MockResearchMockRecorder) DeleteByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockResearch)(nil).DeleteByID), id)
}
