// Code generated by MockGen. DO NOT EDIT.
// Source: society.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	gomock "github.com/golang/mock/gomock"
	entity "homepage/pkg/domain/entity"
	reflect "reflect"
)

// MockSociety is a mock of Society interface
type MockSociety struct {
	ctrl     *gomock.Controller
	recorder *MockSocietyMockRecorder
}

// MockSocietyMockRecorder is the mock recorder for MockSociety
type MockSocietyMockRecorder struct {
	mock *MockSociety
}

// NewMockSociety creates a new mock instance
func NewMockSociety(ctrl *gomock.Controller) *MockSociety {
	mock := &MockSociety{ctrl: ctrl}
	mock.recorder = &MockSocietyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSociety) EXPECT() *MockSocietyMockRecorder {
	return m.recorder
}

// GetAll mocks base method
func (m *MockSociety) GetAll() ([]*entity.Society, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]*entity.Society)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll
func (mr *MockSocietyMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockSociety)(nil).GetAll))
}

// GetByID mocks base method
func (m *MockSociety) GetByID(id int) (*entity.Society, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*entity.Society)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID
func (mr *MockSocietyMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSociety)(nil).GetByID), id)
}

// Create mocks base method
func (m *MockSociety) Create(title, author, society, award, date string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", title, author, society, award, date)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockSocietyMockRecorder) Create(title, author, society, award, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSociety)(nil).Create), title, author, society, award, date)
}

// UpdateByID mocks base method
func (m *MockSociety) UpdateByID(id int, title, author, society, award, date string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", id, title, author, society, award, date)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID
func (mr *MockSocietyMockRecorder) UpdateByID(id, title, author, society, award, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockSociety)(nil).UpdateByID), id, title, author, society, award, date)
}

// DeleteByID mocks base method
func (m *MockSociety) DeleteByID(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID
func (mr *MockSocietyMockRecorder) DeleteByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockSociety)(nil).DeleteByID), id)
}
