// Code generated by MockGen. DO NOT EDIT.
// Source: user.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	gomock "github.com/golang/mock/gomock"
	entity "homepage/pkg/domain/entity"
	reflect "reflect"
)

// MockUser is a mock of User interface
type MockUser struct {
	ctrl     *gomock.Controller
	recorder *MockUserMockRecorder
}

// MockUserMockRecorder is the mock recorder for MockUser
type MockUserMockRecorder struct {
	mock *MockUser
}

// NewMockUser creates a new mock instance
func NewMockUser(ctrl *gomock.Controller) *MockUser {
	mock := &MockUser{ctrl: ctrl}
	mock.recorder = &MockUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUser) EXPECT() *MockUserMockRecorder {
	return m.recorder
}

// GetAll mocks base method
func (m *MockUser) GetAll() ([]*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll
func (mr *MockUserMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockUser)(nil).GetAll))
}

// GetByID mocks base method
func (m *MockUser) GetByID(userID int) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", userID)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID
func (mr *MockUserMockRecorder) GetByID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUser)(nil).GetByID), userID)
}

// GetByStudentID mocks base method
func (m *MockUser) GetByStudentID(studentID string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByStudentID", studentID)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByStudentID indicates an expected call of GetByStudentID
func (mr *MockUserMockRecorder) GetByStudentID(studentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByStudentID", reflect.TypeOf((*MockUser)(nil).GetByStudentID), studentID)
}

// UpdateByID mocks base method
func (m *MockUser) UpdateByID(userID int, name, studentID, department, comment string, grade int) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", userID, name, studentID, department, comment, grade)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateByID indicates an expected call of UpdateByID
func (mr *MockUserMockRecorder) UpdateByID(userID, name, studentID, department, comment, grade interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockUser)(nil).UpdateByID), userID, name, studentID, department, comment, grade)
}

// UpdatePasswordByStudentID mocks base method
func (m *MockUser) UpdatePasswordByStudentID(studentID, oldPassword, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePasswordByStudentID", studentID, oldPassword, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePasswordByStudentID indicates an expected call of UpdatePasswordByStudentID
func (mr *MockUserMockRecorder) UpdatePasswordByStudentID(studentID, oldPassword, newPassword interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePasswordByStudentID", reflect.TypeOf((*MockUser)(nil).UpdatePasswordByStudentID), studentID, oldPassword, newPassword)
}

// AuthenticationByStudentID mocks base method
func (m *MockUser) AuthenticationByStudentID(studentID, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticationByStudentID", studentID, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// AuthenticationByStudentID indicates an expected call of AuthenticationByStudentID
func (mr *MockUserMockRecorder) AuthenticationByStudentID(studentID, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticationByStudentID", reflect.TypeOf((*MockUser)(nil).AuthenticationByStudentID), studentID, password)
}

// AdminAuthorizationByStudentID mocks base method
func (m *MockUser) AdminAuthorizationByStudentID(studentID, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminAuthorizationByStudentID", studentID, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdminAuthorizationByStudentID indicates an expected call of AdminAuthorizationByStudentID
func (mr *MockUserMockRecorder) AdminAuthorizationByStudentID(studentID, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminAuthorizationByStudentID", reflect.TypeOf((*MockUser)(nil).AdminAuthorizationByStudentID), studentID, password)
}

// AdminCreate mocks base method
func (m *MockUser) AdminCreate(name, studentID, password, role, department, comment string, grade int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminCreate", name, studentID, password, role, department, comment, grade)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminCreate indicates an expected call of AdminCreate
func (mr *MockUserMockRecorder) AdminCreate(name, studentID, password, role, department, comment, grade interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminCreate", reflect.TypeOf((*MockUser)(nil).AdminCreate), name, studentID, password, role, department, comment, grade)
}

// AdminUpdate mocks base method
func (m *MockUser) AdminUpdate(userID int, name, studentID, role, department, comment string, grade int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminUpdate", userID, name, studentID, role, department, comment, grade)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdminUpdate indicates an expected call of AdminUpdate
func (mr *MockUserMockRecorder) AdminUpdate(userID, name, studentID, role, department, comment, grade interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminUpdate", reflect.TypeOf((*MockUser)(nil).AdminUpdate), userID, name, studentID, role, department, comment, grade)
}

// DeleteByID mocks base method
func (m *MockUser) DeleteByID(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID
func (mr *MockUserMockRecorder) DeleteByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockUser)(nil).DeleteByID), id)
}
