// Code generated by MockGen. DO NOT EDIT.
// Source: equipment.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	gomock "github.com/golang/mock/gomock"
	entity "homepage/pkg/domain/entity"
	reflect "reflect"
)

// MockEquipmentRepository is a mock of EquipmentRepository interface
type MockEquipmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEquipmentRepositoryMockRecorder
}

// MockEquipmentRepositoryMockRecorder is the mock recorder for MockEquipmentRepository
type MockEquipmentRepositoryMockRecorder struct {
	mock *MockEquipmentRepository
}

// NewMockEquipmentRepository creates a new mock instance
func NewMockEquipmentRepository(ctrl *gomock.Controller) *MockEquipmentRepository {
	mock := &MockEquipmentRepository{ctrl: ctrl}
	mock.recorder = &MockEquipmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockEquipmentRepository) EXPECT() *MockEquipmentRepositoryMockRecorder {
	return m.recorder
}

// FindAll mocks base method
func (m *MockEquipmentRepository) FindAll() ([]*entity.Equipment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]*entity.Equipment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll
func (mr *MockEquipmentRepositoryMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockEquipmentRepository)(nil).FindAll))
}

// FindByID mocks base method
func (m *MockEquipmentRepository) FindByID(id int) (*entity.Equipment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*entity.Equipment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID
func (mr *MockEquipmentRepositoryMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockEquipmentRepository)(nil).FindByID), id)
}

// Create mocks base method
func (m *MockEquipmentRepository) Create(arg0 *entity.Equipment) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockEquipmentRepositoryMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEquipmentRepository)(nil).Create), arg0)
}

// UpdateByID mocks base method
func (m *MockEquipmentRepository) UpdateByID(arg0 *entity.Equipment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID
func (mr *MockEquipmentRepositoryMockRecorder) UpdateByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockEquipmentRepository)(nil).UpdateByID), arg0)
}

// DeleteByID mocks base method
func (m *MockEquipmentRepository) DeleteByID(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID
func (mr *MockEquipmentRepositoryMockRecorder) DeleteByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockEquipmentRepository)(nil).DeleteByID), id)
}
