// Code generated by MockGen. DO NOT EDIT.
// Source: society.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	gomock "github.com/golang/mock/gomock"
	entity "homepage/pkg/domain/entity"
	reflect "reflect"
)

// MockSocietyRepository is a mock of SocietyRepository interface
type MockSocietyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSocietyRepositoryMockRecorder
}

// MockSocietyRepositoryMockRecorder is the mock recorder for MockSocietyRepository
type MockSocietyRepositoryMockRecorder struct {
	mock *MockSocietyRepository
}

// NewMockSocietyRepository creates a new mock instance
func NewMockSocietyRepository(ctrl *gomock.Controller) *MockSocietyRepository {
	mock := &MockSocietyRepository{ctrl: ctrl}
	mock.recorder = &MockSocietyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSocietyRepository) EXPECT() *MockSocietyRepositoryMockRecorder {
	return m.recorder
}

// FindAll mocks base method
func (m *MockSocietyRepository) FindAll() ([]*entity.Society, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]*entity.Society)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll
func (mr *MockSocietyRepositoryMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockSocietyRepository)(nil).FindAll))
}

// FindByID mocks base method
func (m *MockSocietyRepository) FindByID(id int) (*entity.Society, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*entity.Society)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID
func (mr *MockSocietyRepositoryMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockSocietyRepository)(nil).FindByID), id)
}

// Create mocks base method
func (m *MockSocietyRepository) Create(arg0 *entity.Society) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockSocietyRepositoryMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSocietyRepository)(nil).Create), arg0)
}

// UpdateByID mocks base method
func (m *MockSocietyRepository) UpdateByID(arg0 *entity.Society) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID
func (mr *MockSocietyRepositoryMockRecorder) UpdateByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockSocietyRepository)(nil).UpdateByID), arg0)
}

// DeleteByID mocks base method
func (m *MockSocietyRepository) DeleteByID(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID
func (mr *MockSocietyRepositoryMockRecorder) DeleteByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockSocietyRepository)(nil).DeleteByID), id)
}
