// Code generated by MockGen. DO NOT EDIT.
// Source: activity.go

// Package mock_handler is a generated GoMock package.
package mock_handler

import (
	gomock "github.com/golang/mock/gomock"
	http "net/http"
	reflect "reflect"
)

// MockActivityHandler is a mock of ActivityHandler interface
type MockActivityHandler struct {
	ctrl     *gomock.Controller
	recorder *MockActivityHandlerMockRecorder
}

// MockActivityHandlerMockRecorder is the mock recorder for MockActivityHandler
type MockActivityHandlerMockRecorder struct {
	mock *MockActivityHandler
}

// NewMockActivityHandler creates a new mock instance
func NewMockActivityHandler(ctrl *gomock.Controller) *MockActivityHandler {
	mock := &MockActivityHandler{ctrl: ctrl}
	mock.recorder = &MockActivityHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockActivityHandler) EXPECT() *MockActivityHandlerMockRecorder {
	return m.recorder
}

// GetActivities mocks base method
func (m *MockActivityHandler) GetActivities(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetActivities", w, r)
}

// GetActivities indicates an expected call of GetActivities
func (mr *MockActivityHandlerMockRecorder) GetActivities(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivities", reflect.TypeOf((*MockActivityHandler)(nil).GetActivities), w, r)
}

// AdminGetAll mocks base method
func (m *MockActivityHandler) AdminGetAll(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AdminGetAll", w, r)
}

// AdminGetAll indicates an expected call of AdminGetAll
func (mr *MockActivityHandlerMockRecorder) AdminGetAll(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminGetAll", reflect.TypeOf((*MockActivityHandler)(nil).AdminGetAll), w, r)
}

// AdminGetByID mocks base method
func (m *MockActivityHandler) AdminGetByID(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AdminGetByID", w, r)
}

// AdminGetByID indicates an expected call of AdminGetByID
func (mr *MockActivityHandlerMockRecorder) AdminGetByID(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminGetByID", reflect.TypeOf((*MockActivityHandler)(nil).AdminGetByID), w, r)
}

// AdminCreate mocks base method
func (m *MockActivityHandler) AdminCreate(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AdminCreate", w, r)
}

// AdminCreate indicates an expected call of AdminCreate
func (mr *MockActivityHandlerMockRecorder) AdminCreate(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminCreate", reflect.TypeOf((*MockActivityHandler)(nil).AdminCreate), w, r)
}

// AdminUpdateByID mocks base method
func (m *MockActivityHandler) AdminUpdateByID(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AdminUpdateByID", w, r)
}

// AdminUpdateByID indicates an expected call of AdminUpdateByID
func (mr *MockActivityHandlerMockRecorder) AdminUpdateByID(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminUpdateByID", reflect.TypeOf((*MockActivityHandler)(nil).AdminUpdateByID), w, r)
}

// AdminDeleteByID mocks base method
func (m *MockActivityHandler) AdminDeleteByID(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AdminDeleteByID", w, r)
}

// AdminDeleteByID indicates an expected call of AdminDeleteByID
func (mr *MockActivityHandlerMockRecorder) AdminDeleteByID(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminDeleteByID", reflect.TypeOf((*MockActivityHandler)(nil).AdminDeleteByID), w, r)
}
