// Code generated by MockGen. DO NOT EDIT.
// Source: equipment.go

// Package mock_handler is a generated GoMock package.
package mock_handler

import (
	gomock "github.com/golang/mock/gomock"
	http "net/http"
	reflect "reflect"
)

// MockEquipmentHandler is a mock of EquipmentHandler interface
type MockEquipmentHandler struct {
	ctrl     *gomock.Controller
	recorder *MockEquipmentHandlerMockRecorder
}

// MockEquipmentHandlerMockRecorder is the mock recorder for MockEquipmentHandler
type MockEquipmentHandlerMockRecorder struct {
	mock *MockEquipmentHandler
}

// NewMockEquipmentHandler creates a new mock instance
func NewMockEquipmentHandler(ctrl *gomock.Controller) *MockEquipmentHandler {
	mock := &MockEquipmentHandler{ctrl: ctrl}
	mock.recorder = &MockEquipmentHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockEquipmentHandler) EXPECT() *MockEquipmentHandlerMockRecorder {
	return m.recorder
}

// GetAll mocks base method
func (m *MockEquipmentHandler) GetAll(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetAll", w, r)
}

// GetAll indicates an expected call of GetAll
func (mr *MockEquipmentHandlerMockRecorder) GetAll(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockEquipmentHandler)(nil).GetAll), w, r)
}

// AdminGetAll mocks base method
func (m *MockEquipmentHandler) AdminGetAll(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AdminGetAll", w, r)
}

// AdminGetAll indicates an expected call of AdminGetAll
func (mr *MockEquipmentHandlerMockRecorder) AdminGetAll(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminGetAll", reflect.TypeOf((*MockEquipmentHandler)(nil).AdminGetAll), w, r)
}

// AdminGetByID mocks base method
func (m *MockEquipmentHandler) AdminGetByID(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AdminGetByID", w, r)
}

// AdminGetByID indicates an expected call of AdminGetByID
func (mr *MockEquipmentHandlerMockRecorder) AdminGetByID(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminGetByID", reflect.TypeOf((*MockEquipmentHandler)(nil).AdminGetByID), w, r)
}

// AdminCreate mocks base method
func (m *MockEquipmentHandler) AdminCreate(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AdminCreate", w, r)
}

// AdminCreate indicates an expected call of AdminCreate
func (mr *MockEquipmentHandlerMockRecorder) AdminCreate(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminCreate", reflect.TypeOf((*MockEquipmentHandler)(nil).AdminCreate), w, r)
}

// AdminUpdateByID mocks base method
func (m *MockEquipmentHandler) AdminUpdateByID(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AdminUpdateByID", w, r)
}

// AdminUpdateByID indicates an expected call of AdminUpdateByID
func (mr *MockEquipmentHandlerMockRecorder) AdminUpdateByID(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminUpdateByID", reflect.TypeOf((*MockEquipmentHandler)(nil).AdminUpdateByID), w, r)
}

// AdminDeleteByID mocks base method
func (m *MockEquipmentHandler) AdminDeleteByID(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AdminDeleteByID", w, r)
}

// AdminDeleteByID indicates an expected call of AdminDeleteByID
func (mr *MockEquipmentHandlerMockRecorder) AdminDeleteByID(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminDeleteByID", reflect.TypeOf((*MockEquipmentHandler)(nil).AdminDeleteByID), w, r)
}
