# default: &default
#   adapter: mysql2
#   encoding: utf8
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   username: root
#   password:
#   host: localhost

default: &default
  adapter: sqlite3
  encoding: utf8
  pool: 5
  timeout: 5000

## development DB Settings
development:
  <<: *default
  database: db/development.sqlite3

## test DB Settings
test:
  <<: *default
  database: db/test.sqlite3

## production DB Settings
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: homepage
  pool: 5
  username: homepage
  password: sorejavadedekinaino
