// login関連
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

// sagaでapiを叩くための子たち...
export const FETCH_ACTIVITIES = "FETCH_ACTIVITIES"
export const LOADED_ACTIVITIES = "LOADED_ACTIVITIES"

export const FETCH_SOCIETIES = "FETCH_SOCIETIES"
export const LOADED_SOCIETIES = "LOADED_SOCIETIES"

export const FETCH_RESEARCHES = "FETCH_RESEARCHES"
export const LOADED_RESEARCHES = "LOADED_RESEARCHES"

export const FETCH_MEMBERS = "FETCH_MEMBERS"
export const LOADED_MEMBERS = "LOADED_MEMBERS"
export const FETCH_MEMBER = "FETCH_MEMBER"
export const LOADED_MEMBER = "LOADED_MEMBER"

export const UPDATE_MEMBER_REQUEST = "UPDATE_MEMBER_REQUEST"
export const UPDATE_MEMBER_SUCCESS = "UPDATE_MEMBER_SUCCESS"
export const UPDATE_MEMBER_FAILURE = "UPDATE_MEMBER_FAILURE"

export const FETCH_JOBS = "FETCH_JOBS"
export const LOADED_JOBS = "LOADED_JOBS"

export const FETCH_EQUIPMENTS = "FETCH_EQUIPMENTS"
export const LOADED_EQUIPMENTS = "LOADED_EQUIPMENTS"

export const FETCH_LECTURES = "FETCH_LECTURES"
export const LOADED_LECTURES = "LOADED_LECTURES"

// connection api
export const API_ERROR = "API_ERROR"

// switch loading state
export const SHOW_LOADING = "SHOW_LOADING"
export const HIDE_LOADING = "HIDE_LOADING"

