// login関連
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const LOGOUT_REQUEST = "LOGOUT_REQUEST"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAILURE = "LOGOUT_FAILURE"

// account
export const FETCH_ACCOUNT_REQUEST = "FETCH_ACCOUNT_REQUEST"
export const FETCH_ACCOUNT_SUCCESS = "FETCH_ACCOUNT_SUCCESS"
export const FETCH_ACCOUNT_FAILURE = "FETCH_ACCOUNT_FAILURE"

export const UPDATE_ACCOUNT_REQUEST = "UPDATE_ACCOUNT_REQUEST"
export const UPDATE_ACCOUNT_SUCCESS = "UPDATE_ACCOUNT_SUCCESS"
export const UPDATE_ACCOUNT_FAILURE = "UPDATE_ACCOUNT_FAILURE"
export const UPDATE_ACCOUNT_PASSWORD_REQUEST = "UPDATE_ACCOUNT_PASSWORD_REQUEST"
export const UPDATE_ACCOUNT_PASSWORD_SUCCESS = "UPDATE_ACCOUNT_PASSWORD_SUCCESS"
export const UPDATE_ACCOUNT_PASSWORD_FAILURE = "UPDATE_ACCOUNT_PASSWORD_FAILURE"

// activity
export const FETCH_ACTIVITIES_REQUEST = "FETCH_ACTIVITIES_REQUEST"
export const FETCH_ACTIVITIES_SUCCESS = "FETCH_ACTIVITIES_SUCCESS"
export const FETCH_ACTIVITIES_FAILURE = "FETCH_ACTIVITIES_FAILURE"

// society
export const FETCH_SOCIETIES_REQUEST = "FETCH_SOCIETIES_REQUEST"
export const FETCH_SOCIETIES_SUCCESS = "FETCH_SOCIETIES_SUCCESS"
export const FETCH_SOCIETIES_FAILURE = "FETCH_SOCIETIES_FAILURE"

// research
export const FETCH_RESEARCHES_REQUEST = "FETCH_RESEARCHES_REQUEST"
export const FETCH_RESEARCHES_SUCCESS = "FETCH_RESEARCHES_SUCCESS"
export const FETCH_RESEARCHES_FAILURE = "FETCH_RESEARCHES_FAILURE"

// member
export const FETCH_MEMBERS_REQUEST = "FETCH_MEMBERS_REQUEST"
export const FETCH_MEMBERS_SUCCESS = "FETCH_MEMBERS_SUCCESS"
export const FETCH_MEMBERS_FAILURE = "FETCH_MEMBERS_FAILURE"

export const FETCH_MEMBER_REQUEST = "FETCH_MEMBER_REQUEST"
export const FETCH_MEMBER_SUCCESS = "FETCH_MEMBER_SUCCESS"
export const FETCH_MEMBER_FAILURE = "FETCH_MEMBER_FAILURE"

export const UPDATE_MEMBER_REQUEST = "UPDATE_MEMBER_REQUEST"
export const UPDATE_MEMBER_SUCCESS = "UPDATE_MEMBER_SUCCESS"
export const UPDATE_MEMBER_FAILURE = "UPDATE_MEMBER_FAILURE"

// job
export const FETCH_JOBS_REQUEST = "FETCH_JOBS_REQUEST"
export const FETCH_JOBS_SUCCESS = "FETCH_JOBS_SUCCESS"
export const FETCH_JOBS_FAILURE = "FETCH_JOBS_FAILURE"

// equipment
export const FETCH_EQUIPMENTS_REQUEST = "FETCH_EQUIPMENTS_REQUEST"
export const FETCH_EQUIPMENTS_SUCCESS = "FETCH_EQUIPMENTS_SUCCESS"
export const FETCH_EQUIPMENTS_FAILURE = "FETCH_EQUIPMENTS_FAILURE"

// lecture
export const FETCH_LECTURES_REQUEST = "FETCH_LECTURES_REQUEST"
export const FETCH_LECTURES_SUCCESS = "FETCH_LECTURES_SUCCESS"
export const FETCH_LECTURES_FAILURE = "FETCH_LECTURES_FAILURE"
export const FETCH_LECTURE_REQUEST = "FETCH_LECTURE_REQUEST"
export const FETCH_LECTURE_SUCCESS = "FETCH_LECTURE_SUCCESS"
export const FETCH_LECTURE_FAILURE = "FETCH_LECTURE_FAILURE"

export const CREATE_LECTURE_REQUEST = "CREATE_LECTURE_REQUEST"
export const CREATE_LECTURE_SUCCESS = "CREATE_LECTURE_SUCCESS"
export const CREATE_LECTURE_FAILURE = "CREATE_LECTURE_FAILURE"

// connection api. 
export const API_ERROR = "API_ERROR"

// switch loading state
export const SHOW_LOADING = "SHOW_LOADING"
export const HIDE_LOADING = "HIDE_LOADING"

