// Code generated by MockGen. DO NOT EDIT.
// Source: lecture.go

// Package mock_controller is a generated GoMock package.
package mock_controller

import (
	gomock "github.com/golang/mock/gomock"
	controller "homepage/pkg/interface/controller"
	reflect "reflect"
)

// MockLectureController is a mock of LectureController interface
type MockLectureController struct {
	ctrl     *gomock.Controller
	recorder *MockLectureControllerMockRecorder
}

// MockLectureControllerMockRecorder is the mock recorder for MockLectureController
type MockLectureControllerMockRecorder struct {
	mock *MockLectureController
}

// NewMockLectureController creates a new mock instance
func NewMockLectureController(ctrl *gomock.Controller) *MockLectureController {
	mock := &MockLectureController{ctrl: ctrl}
	mock.recorder = &MockLectureControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockLectureController) EXPECT() *MockLectureControllerMockRecorder {
	return m.recorder
}

// GetAll mocks base method
func (m *MockLectureController) GetAll() (*controller.LecturesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].(*controller.LecturesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll
func (mr *MockLectureControllerMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockLectureController)(nil).GetAll))
}

// GetByID mocks base method
func (m *MockLectureController) GetByID(id int) (*controller.LectureResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*controller.LectureResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID
func (mr *MockLectureControllerMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockLectureController)(nil).GetByID), id)
}

// Create mocks base method
func (m *MockLectureController) Create(studentID, title, file, comment string, activation int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", studentID, title, file, comment, activation)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockLectureControllerMockRecorder) Create(studentID, title, file, comment, activation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLectureController)(nil).Create), studentID, title, file, comment, activation)
}

// UpdateByID mocks base method
func (m *MockLectureController) UpdateByID(id int, studentID, title, file, comment string, activation int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", id, studentID, title, file, comment, activation)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID
func (mr *MockLectureControllerMockRecorder) UpdateByID(id, studentID, title, file, comment, activation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockLectureController)(nil).UpdateByID), id, studentID, title, file, comment, activation)
}

// DeleteByID mocks base method
func (m *MockLectureController) DeleteByID(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID
func (mr *MockLectureControllerMockRecorder) DeleteByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockLectureController)(nil).DeleteByID), id)
}

// AdminGetAll mocks base method
func (m *MockLectureController) AdminGetAll() ([]map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminGetAll")
	ret0, _ := ret[0].([]map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminGetAll indicates an expected call of AdminGetAll
func (mr *MockLectureControllerMockRecorder) AdminGetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminGetAll", reflect.TypeOf((*MockLectureController)(nil).AdminGetAll))
}

// AdminGetByID mocks base method
func (m *MockLectureController) AdminGetByID(id int) (*controller.FieldsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminGetByID", id)
	ret0, _ := ret[0].(*controller.FieldsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminGetByID indicates an expected call of AdminGetByID
func (mr *MockLectureControllerMockRecorder) AdminGetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminGetByID", reflect.TypeOf((*MockLectureController)(nil).AdminGetByID), id)
}
